version: "3.2"
services:
  
  bind:
    image: nginx:1.0
    container_name: bind
    hostname: bind.local # Webmin server clustering seems to work better with the actual hostname you will be setting in DNS
    volumes:
      - ./data:/data
    ports:
      - 10000:10000
      - 53:53
      - 53:53/udp
    environment:
      TZ : America/Regina
      ROOT_PASSWORD : Password        # Set the Root Password
    restart: unless-stopped

