version: "3.2"
services:
  
  bind:
    image: polargeek/bind-webmin:latest
    container_name: bind
    volumes:
      - ./data:/data
    ports:
      - 10000:10000
      - 53:53
      - 53:53/udp
    environment:
      TZ : America/Regina
      ROOT_PASSWORD : Password
    restart: unless-stopped

